theme: jekyll-theme-cayman
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Deb Sankar's homepage
description: My research on the physics of living systems
classes: wide
github:
  is_project_page: false
